In [1]:
import pickle
import numpy as np

In [4]:
ohe_sex = pickle.load(open('Models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('Models/ohe_embarked.pkl','rb'))
model = pickle.load(open('Models/model.pkl','rb'))

In [7]:
#Assume user input
#Pclass/gender/age/sibsp/parch/fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [8]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [14]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

C:\Users\itsri\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [16]:
test_input_embarked = ohe_embarked.transform(test_input[:,6].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [17]:
test_input_age = test_input[:,2].reshape(1,1)

In [27]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]].reshape(1,4),test_input_age,test_input_sex,test_input_embarked),a)

In [28]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 0.0, 1.0, 0.0, 1.0]], dtype=object)

In [29]:
model.predict(test_input_transformed)

array([0], dtype=int64)